name: Renovate

on:
  schedule:
    - cron:  '18 21 * * *'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Install NDK
        run: echo "y" | sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;21.0.6113669" --sdk_root=${ANDROID_SDK_ROOT}
      - name: "Install OpenCV"
        run: "./setup_opencv_android.sh"
      - uses: Djiit/action-renovate@master
        with:
          args: >
            ${{ github.repository }}
          # --more-args
        env:
          RENOVATE_TOKEN: ${{ secrets.RENOVATE_TOKEN }}
